src/Web/Controllers/BasketController.cs
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Interfaces;
using Web.ViewModels;

namespace Web.Controllers
{
    public class BasketController : Controller
    {
        private readonly IBasketViewModelService _basketViewModelService;
        private readonly IBasketService _basketService;
        private readonly IOrderService _orderService;
        private readonly IOrderViewModelService _orderViewModelService;

        public BasketController(IBasketViewModelService basketViewModelService, IBasketService basketService, IOrderService orderService, IOrderViewModelService orderViewModelService)
        {
            _basketViewModelService = basketViewModelService;
            _basketService = basketService;
            _orderService = orderService;
            _orderViewModelService = orderViewModelService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _basketViewModelService.GetBasketViewModel());
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToBasket(int productId, int quantity)
        {
            var basketId = await _basketViewModelService.GetOrCreateBasketIdAsync();
            await _basketService.AddItemToBasket(basketId, productId, quantity);
            //int basketItemsCount = await _basketService.BasketItemCount(basketId);
            //return Json(new BasketItemsCountViewModel() { BasketItemsCount = basketItemsCount });
            return Json(await _basketViewModelService.GetBasketItemsCountViewModel(basketId));
        }
        [HttpPost]
        public async Task<IActionResult> RemoveBasketItem(int basketItemId)
        {
            var basketId = await _basketViewModelService.GetOrCreateBasketIdAsync();
            await _basketService.DeleteBasketItem(basketId, basketItemId);
            return PartialView("_BasketPartial", await _basketViewModelService.GetBasketViewModel());
        }
        [HttpPost]
        public async Task<IActionResult> UpdateBasketItem(int basketItemId, int quantity)
        {
            if (quantity < 1) return BadRequest("The quantity cannot be less than 1.");
            var basketId = await _basketViewModelService.GetOrCreateBasketIdAsync();
            await _basketService.UpdateBasketItem(basketId, basketItemId, quantity);
            return PartialView("_BasketPartial", await _basketViewModelService.GetBasketViewModel());
        }

        [Authorize]
        public async Task<IActionResult> Checkout()
        {
            var vm = new CheckoutViewModel()
            {
                BasketItems = await _basketViewModelService.GetBasketItems()
            };
            return View(vm);
        }
        [Authorize,HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Checkout(CheckoutViewModel model)
        {
            if (ModelState.IsValid)
            {
                int basketId = await _basketViewModelService.GetOrCreateBasketIdAsync();
                // Process the payment
                // Place the order
                var address = new Address()
                {
                    City = model.City,
                    Country = model.Country,
                    State = model.State,
                    ZipCode = model.ZipCode,
                    Street = model.Street
                };
                await _orderService.CreateOrderAsync(basketId, address);
                //delete the basket
                await _basketService.DeleteBasketAsync(basketId);

                return RedirectToAction("Success");
            }
            model.BasketItems = await _basketViewModelService.GetBasketItems();
            return View(model);
        }

        public IActionResult Success()
        {
            return View();
        }
        [Authorize]
        public async Task<IActionResult> Orders()
        {
            return View(await _orderViewModelService.ListOrdersAsync());
        }
        [Authorize]
        public async Task<IActionResult> OrderDetails(int? id)
        {
            if (id == null || id < 0)
            {
                return NotFound();
            }
            return View(await _orderViewModelService.ListOrderItemsAsync((int)id));
        }

    }
}

src/Web/Controllers/HomeController.cs
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Web.Interfaces;
using Web.Models;
using Web.ViewModels;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IHomeViewModelService _homeViewModelService;

        public HomeController(ILogger<HomeController> logger, IHomeViewModelService homeViewModelService)
        {
            _logger = logger;
            _homeViewModelService = homeViewModelService;
            //_productRepository = productRepository;//application core'a bağlıyız dolayısıyla interface üzerinden çalışıyoruz.
        }

        public async Task<IActionResult> Index(HomeIndexViewModel vm, int page = 1)
        {
            return View(await _homeViewModelService.GetHomeIndexViewModel(vm.CategoryId, vm.AuthorId, page, Constans.ITEMS_PER_PAGE));
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Web/Views/Home/Index.cshtml
@model HomeIndexViewModel
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Xsrf
@*https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-5.0#javascript*@

@{
    ViewData["Title"] = "Home Page";
    var token = Xsrf.GetAndStoreTokens(Context).RequestToken;
}
<form class="form-inline py-3">
    <label class="mr-1">Category:</label>
    <select asp-for="CategoryId" asp-items="Model.Categories" class="form-control mr-0 mr-sm-2"></select>
    <label class="mr-1 mt-2 mt-sm-0">Author:</label>
    <select asp-for="AuthorId" asp-items="Model.Authors" class="form-control"></select>
</form>

<div class="row mx-md-n2">
    @foreach (var item in Model.Products)
    {
        <div class="col-md-3 px-md-2 mb-3 align-items-center d-flex flex-column border p-2">
            <div class="product-image-wrapper">
                <img src="~/img/@item.PictureUri" class="product-image" />
            </div>
            <div class="product-name">
                @item.Name
            </div>
            <div class="author-name">
                @item.AuthorName
            </div>
            <div class="product-price mb-2">
                @item.Price.ToString("c2")
            </div>
            <button class="btn btn-success mt-auto" data-add-to-basket="@item.Id"><i class="fas fa-cart-plus"></i></button>
        </div>
    }
</div>

<partial name="_PaginationPartial" model="Model.PaginationInfo">

    @section scripts{
        <script>
            $("#CategoryId, #AuthorId").change(function () {
                $(this).closest("form").submit();
            });

            $("[data-add-to-basket]").click(function (event) {
                event.preventDefault();
                var productId = $(this).data("add-to-basket");

                $.ajax({
                    type: "post",
                    url: "@Url.Action("AddToBasket","Basket")",
                    headers: {
                        RequestVerificationToken: "@token" //tokens başlıkta gidiyor.
                    },
                    data: {
                        productId: productId,
                        quantity: 1
                    },
                    success: function (data) {
                        $("#navBasketItemsCount").text(data.basketItemsCount);//json olduğu için ilk harf küçük geliyor.
                        toastr.success("The item has been added to the basket.")
                    }
                });
            });
        </script>
    }